sudo: required
  
services:
  - docker
  - postgresql

language: scala

scala:
  - 2.11.8

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - psql -h localhost --username="postgres" -f sql/ddl.sql

script:
  - ./sbtw clean compile docker:publishLocal
  - ./compose run --rm vendor_proxy_acc_tests

after_success:
  - sbt docker:publish

cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.sbt"

# blacklist
branches:
  except:
    - RELEASE
