sudo: required
  
services:
  - docker

language: java

jdk: openjdk11

scala:
  - 2.12.10

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

before_script:
  - sudo /etc/init.d/postgresql stop

script:
  - ./sbtw clean compile docker:publishLocal
  - ./compose up -d
  - ./sbtw test

after_script:
  - ./compose down

after_success:
  - sbt docker:publish

cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.sbt"

# blacklist
branches:
  except:
    - RELEASE

notifications:
  slack: sdkman:QdA1XVUuYDjlYL4Z7gm16OEc
