sudo: required
  
services:
  - docker

language: scala

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

before_script:
  - sudo /etc/init.d/postgresql stop

script:
  - sbt clean compile docker:publishLocal
  - ./compose up -d
  - sbt test

after_script:
  - ./compose down

cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.sbt"

# blacklist
branches:
  except:
    - RELEASE

notifications:
  slack: sdkman:QdA1XVUuYDjlYL4Z7gm16OEc
