version: '2'

services:
  postgres:
    container_name: postgres
    image: postgres:15
    ports:
     - "5432:5432"
    environment:
      POSTGRES_USER: "vendors"
      POSTGRES_PASSWORD: "vendors"
      POSTGRES_DB: "vendors"

