version: '2'

services:

  wiremock:
    container_name: wiremock
    image: rodolpheche/wiremock:latest
    ports:
      - "8080:8080"
      - "8081:8081"

  postgres:
    container_name: postgres
    image: postgres:9.5.2
    ports:
     - "5432:5432"
    environment:
      POSTGRES_USER: "vendors"
      POSTGRES_DB: "vendors"

